#!/bin/bash
############################
# sync.sh
# This script merges a number of config_ files to create a working .ssh/config file.
# Any custom file named config_* will be included in the merge, in alphanumerical order.
# /!\ No conflict detection, be careful and check the final file manually. /!\
############################

########## Variables
SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ssh=~/.ssh                       # .ssh directory
repo=$SCRIPT_PATH               # repository directory
dir=$repo/ssh                    # ssh directory
olddir=$repo/ssh_bak             # backup directory

##########

# create ssh_old in homedir
echo -n "Creating $olddir for backup of any existing dotfiles in ~..."
echo ""
echo "mkdir -p $olddir"
mkdir -p $olddir
echo "Done."

# change to the ssh directory
echo -n "Changing to the $ssh directory..."
echo ""
echo "cd $ssh"
cd $ssh
echo "Done."

echo "Making a backup of $ssh to $olddir..."
echo "mkdir -p $olddir"
mkdir -p $olddir
echo "mv $ssh/* $olddir"
mv $ssh/* $olddir
echo "Done."

echo "==="
echo "Creating the new ssh configuration..."
echo "cd $dir/conf"
cd $dir/conf
echo "Adding the base configuration..."
echo "# Careful: do not edit this file directly; it is generated and your changes will be erased!" > config
echo "Done."
echo "Adding project files..."
for file in `ls config_*`; do
    cat $file >> config
    echo "" >> config
    echo "" >> config
done
echo "Done."
echo "Creating symbolic link"
ln -s $repo/ssh/conf/config $ssh/config
echo "Done."
echo "Done creating $ssh/config."

echo "==="

echo "Copying the keys..."
echo "cd $dir/keys"
cd $dir/keys
echo "cp * $ssh"
cp * $ssh
echo "Done."
echo "==="
cd
echo "Finished."
