#!/bin/bash
############################
# sync.sh
# This script merges a number of config_ files to create a working .ssh/config file.
# Any custom file named config_* will be included in the merge, in alphanumerical order.
# /!\ No conflict detection, be careful and check the final file manually. /!\
############################

########## Variables
SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
now=$(date +"%Y-%m-%d")
ssh=~/.ssh                       # .ssh directory
repo=$SCRIPT_PATH               # repository directory
dir=$repo/ssh                    # ssh directory
sshbak=$repo/ssh_$now             # backup directory

##########
# change to the ssh directory
echo -n "Changing to the $ssh directory..."
pushd $ssh
echo "Done."

echo "Making a backup of $ssh to $sshbak..."
mkdir -p $sshbak
echo "Moving the current $ssh to $sshbak"
cp -R $ssh/* $sshbak
echo "Done."

echo "==="
echo "Creating the new $ssh/config..."
echo "Any existing config will be overwritten. Remember a backup has been made in $sshbak."
cd $dir/conf
echo "Adding the configuration files..."
echo "Tip: you can add custom rules in the configPersonal file."
echo "# Careful: do not edit this file directly; it is generated and your changes will be erased!" > config
echo "" >> config
echo "# Edit/create configPersonal or configSOMETHING instead" >> config
for file in `ls config*`; do
    cat $file >> config
    echo "" >> config
    echo "" >> config
done
echo "Done."
echo "Moving the new config file to $ssh"
mv $repo/ssh/conf/config $ssh/config
echo "Done creating $ssh/config."

echo "==="

echo "Copying the keys..."
echo "Existing keys will be overwritten. Remember a backup has been made in $sshbak."
echo "cd $dir/keys"
cd $dir/keys
echo "cp * $ssh"
cp * $ssh
echo "Done."
echo "==="
popd
echo "Finished."
